// Accord des textes au féminin pour le circuit WTA.

// ─── TEXTES AU FÉMININ (circuit WTA) ─────────────────────────────────────────
// Les textes du jeu sont écrits au masculin. En carrière WTA, ils sont accordés
// au féminin au moment de l'affichage (voir l'effet « feminizeDom » dans
// TennisManager), sans dupliquer les textes. Règles des plus précises aux plus
// générales ; les limites de mots tiennent compte des lettres accentuées.
export const _B = "(?<![\\p{L}\\p{N}])", _E = "(?![\\p{L}\\p{N}])";
export const _fr = (pattern, repl) => [new RegExp(_B + pattern + _E, "gu"), repl];
export const WTA_TEXT_RULES = [
  // Phrases précises (commentaires, interviews, réseaux, événements)
  _fr("est-il le joueur le plus régulier", "est-elle la joueuse la plus régulière"),
  _fr("doit-il revoir son calendrier", "doit-elle revoir son calendrier"),
  _fr("Un ancien champion que", "Une ancienne championne que"),
  _fr("Un junior prometteur de votre académie vous demande de le parrainer", "Une junior prometteuse de votre académie vous demande de la parrainer"),
  _fr("avec un junior aujourd'hui\\. Il a", "avec une junior aujourd'hui. Elle a"),
  _fr("Il me pousse", "Elle me pousse"),
  _fr("C'est lui qui doit", "C'est elle qui doit"),
  _fr("apprendre de lui", "apprendre d'elle"),
  _fr("je le vois en face", "je la vois en face"),
  _fr("Je le respecte", "Je la respecte"),
  _fr("Pas le plus spectaculaire", "Pas la plus spectaculaire"),
  _fr("je suis un spécialiste", "je suis une spécialiste"),
  _fr("je suis un athlète", "je suis une athlète"),
  _fr("On t'a vu super détendu", "On t'a vue super détendue"),
  _fr("trop discret", "trop discrète"),
  _fr("un peu éteint", "un peu éteinte"),
  _fr("Un grand serveur-volleyeur", "Une grande serveuse-volleyeuse"),
  _fr("Serveur-volleyeur", "Serveuse-volleyeuse"),
  _fr("serveur-volleyeur", "serveuse-volleyeuse"),
  _fr("Concentré, serein", "Concentrée, sereine"),
  _fr("Concentré sur", "Concentrée sur"),
  _fr("(rester|restez) concentré", "$1 concentrée"),
  _fr("Je sors confiant", "Je sors confiante"),
  _fr("Très touché", "Très touchée"),
  _fr("mieux récompensé", "mieux récompensée"),
  _fr("je suis né", "je suis née"),
  _fr("je suis tombé", "je suis tombée"),
  _fr("sortez renforcé", "sortez renforcée"),
  _fr("êtes blanchi", "êtes blanchie"),
  _fr("êtes démasqué", "êtes démasquée"),
  _fr("êtes guéri", "êtes guérie"),
  _fr("êtes gêné", "êtes gênée"),
  _fr("copieusement sifflé", "copieusement sifflée"),
  _fr("Êtes-vous sûr", "Êtes-vous sûre"),
  _fr("l'ambassadeur", "l'ambassadrice"),
  _fr("Adversaire fatigué", "Adversaire fatiguée"),
  _fr("Mené au score, le voilà", "Menée au score, la voilà"),
  _fr("Mené d'un set", "Menée d'un set"),
  _fr("(est|êtes|été|longtemps) mené", "$1 menée"),
  _fr("est breaké", "est breakée"),
  [new RegExp(", breaké" + _E, "gu"), ", breakée"],
  _fr("rester vigilant", "rester vigilante"),
  _fr("semblé inquiété", "semblé inquiétée"),
  _fr("Dos au mur, il a", "Dos au mur, elle a"),
  _fr("On le voyait perdu", "On la voyait perdue"),
  _fr("dominé de la tête", "dominée de la tête"),
  _fr("était trop fort", "était trop forte"),
  _fr("et un (.+?) impressionnant\\.", "et une $1 impressionnante."),
  _fr("où il n'a jamais", "où elle n'a jamais"),
  _fr("qu'il était en bonne posture", "qu'elle était en bonne posture"),
  _fr("est prié", "est priée"),
  _fr("et pourtant il retourne", "et pourtant elle retourne"),
  _fr("et il n'a jamais", "et elle n'a jamais"),
  _fr("On l'a cru", "On l'a crue"),
  _fr("il monte il monte", "elle monte elle monte"),
  _fr("Demi-finalistes éliminés", "Demi-finalistes éliminées"),
  _fr("Gagner un match en 5 sets", "Gagner un match de Grand Chelem en 3 sets"),
  _fr("Les matchs en 5 sets, c'est ça le vrai tennis", "Les matchs en 3 sets, c'est ça le vrai tennis"),
  _fr("Il quitte le circuit", "Elle quitte le circuit"),
  [new RegExp("(\\d+)e mondial\\)", "gu"), "$1e mondiale)"],
  _fr("aussi bien classé", "aussi bien classée"),
  _fr("couronné", "couronnée"),
  // Défis
  _fr("Ancien n°1 mondial", "Ancienne n°1 mondiale"),
  _fr("Le futur n°1 est-il déjà fini", "La future n°1 est-elle déjà finie"),
  _fr("futur n°1", "future n°1"),
  _fr("Votre grand rival de l'époque, désormais retraité", "Votre grande rivale de l'époque, désormais retraitée"),
  _fr("Un jeune du top 50", "Une jeune du top 50"),
  _fr("Le jeune qui vous admire", "La jeune qui vous admire"),
  _fr("êtes surcoté", "êtes surcotée"),
  _fr("seul jusqu'au bout", "seule jusqu'au bout"),
  _fr("Il ne gagnera jamais", "Elle ne gagnera jamais"),
  _fr("Un concurrent", "Une concurrente"),
  [new RegExp("(\\d+)e mondial" + _E, "gu"), "$1e mondiale"],
  _fr("Le n°1 mondial", "La n°1 mondiale"),
  _fr("n°1 mondial", "n°1 mondiale"),
  _fr("représentants", "représentantes"),
  _fr("trop prudent", "trop prudente"),
  _fr("qui t'a marqué", "qui t'a marquée"),
  _fr("a-t-il le physique", "a-t-elle le physique"),
  [new RegExp(_B + "(face à|et|contre) un (?=[\\p{Lu}#])", "gu"), "$1 une "],
  // Trophées et titres de prestige
  _fr("Roi détrôné", "Reine détrônée"),
  _fr("Renard piégé", "Tigresse domptée"),
  _fr("Big Two terrassés", "Big Two terrassées"),
  _fr("Battre C\\. Alcázar", "Battre I. Swiatak"),
  _fr("Battre J\\. Sinterm", "Battre A. Sabalenko"),
  _fr("Battre Sinterm ET Alcázar", "Battre Sabalenko ET Swiatak"),
  [new RegExp(_B + "Roi (du |de l')", "gu"), "Reine $1"],
  _fr("Tueur de géants", "Tueuse de géantes"),
  _fr("Tombeur du Roi", "Tombeuse de la Reine"),
  _fr("Gentleman du gazon", "Lady du gazon"),
  _fr("King of New York", "Queen of New York"),
  _fr("Maître absolu", "Maîtrise absolue"),
  _fr("Chasseur d'élite", "Chasseuse d'élite"),
  _fr("Habitué du circuit", "Habituée du circuit"),
  _fr("Sérieux client", "Sérieuse cliente"),
  _fr("Grand champion", "Grande championne"),
  _fr("Journeyman", "Journeywoman"),
  _fr("Régulier", "Régulière"),
  _fr("Élu", "Élue"),
  _fr("Curieux", "Curieuse"),
  _fr("Terrien", "Terrienne"),
  _fr("Polyvalent", "Polyvalente"),
  _fr("Invaincu", "Invaincue"),
  _fr("Canonnier", "Canonnière"),
  _fr("Collectionneur", "Collectionneuse"),
  // Joueur → joueuse
  _fr("Joueur complet", "Joueuse complète"),
  _fr("Joueur confirmé", "Joueuse confirmée"),
  _fr("un joueur inconnu", "une joueuse inconnue"),
  _fr("joueur inconnu", "joueuse inconnue"),
  _fr("du circuit, classés", "du circuit, classées"),
  _fr("meilleurs joueurs", "meilleures joueuses"),
  _fr("meilleur joueur", "meilleure joueuse"),
  _fr("un autre joueur", "une autre joueuse"),
  _fr("([Uu])n joueur", "$1ne joueuse"),
  _fr("([Ll])e joueur", "$1a joueuse"),
  _fr("du joueur", "de la joueuse"),
  _fr("au joueur", "à la joueuse"),
  _fr("([Cc])e joueur", "$1ette joueuse"),
  _fr("Quel joueur", "Quelle joueuse"),
  [new RegExp("(?<!autres |entre )" + _B + "joueurs" + _E, "gu"), "joueuses"],
  _fr("joueur", "joueuse"),
  _fr("Joueurs", "Joueuses"),
  _fr("Joueur", "Joueuse"),
  // Champion, vainqueur, favori…
  _fr("([Uu])n champion", "$1ne championne"),
  _fr("([Ll])e champion", "$1a championne"),
  _fr("champions", "championnes"),
  _fr("champion", "championne"),
  _fr("Champion", "Championne"),
  _fr("([Ll])e vainqueur", "$1a gagnante"),
  _fr("vainqueurs", "gagnantes"),
  _fr("vainqueur", "gagnante"),
  _fr("Vainqueur", "Gagnante"),
  _fr("plus d'un favori", "plus d'une favorite"),
  _fr("([Ll])e favori", "$1a favorite"),
  _fr("([Uu])n favori", "$1ne favorite"),
  _fr("favoris", "favorites"),
  _fr("favori", "favorite"),
  _fr("([Uu])n finaliste", "$1ne finaliste"),
  _fr("([Ll])e finaliste", "$1a finaliste"),
  _fr("([Uu])n adversaire", "$1ne adversaire"),
  // Accords des participes (la joueuse)
  _fr("Qualifié", "Qualifiée"),
  _fr("qualifié", "qualifiée"),
  _fr("Éliminé", "Éliminée"),
  _fr("Inscrit", "Inscrite"),
  _fr("inscrit", "inscrite"),
  _fr("blessé", "blessée"),
  // Circuit et catégories ITF
  _fr("Challenger \\(hors calendrier\\)", "WTA 125 (hors calendrier)"),
  _fr("ATP", "WTA"),
  _fr("M25", "W35"),
  _fr("M15", "W15"),
];
export function feminizeText(txt) {
  let out = txt;
  for (const [re, rp] of WTA_TEXT_RULES) out = out.replace(re, rp);
  return out;
}
