// Accord des textes au féminin pour le circuit WTA.

// ─── TEXTES AU FÉMININ (circuit WTA) ─────────────────────────────────────────
// Les textes du jeu sont écrits au masculin. En carrière WTA, ils sont accordés
// au féminin au moment de l'affichage (voir l'effet « feminizeDom » dans
// TennisManager), sans dupliquer les textes. Règles des plus précises aux plus
// générales ; les limites de mots tiennent compte des lettres accentuées.
export const _B = "(?<![\\p{L}\\p{N}])", _E = "(?![\\p{L}\\p{N}])";
export const _fr = (pattern, repl) => [new RegExp(_B + pattern + _E, "gu"), repl];
export const WTA_TEXT_RULES = [
  // Phrases précises (commentaires, interviews, réseaux, événements)
  _fr("est-il le joueur le plus régulier", "est-elle la joueuse la plus régulière"),
  _fr("doit-il revoir son calendrier", "doit-elle revoir son calendrier"),
  _fr("Un ancien champion que", "Une ancienne championne que"),
  _fr("Un junior prometteur de votre académie vous demande de le parrainer", "Une junior prometteuse de votre académie vous demande de la parrainer"),
  _fr("avec un junior aujourd'hui\\. Il a", "avec une junior aujourd'hui. Elle a"),
  _fr("Il me pousse", "Elle me pousse"),
  _fr("C'est lui qui doit", "C'est elle qui doit"),
  _fr("apprendre de lui", "apprendre d'elle"),
  _fr("je le vois en face", "je la vois en face"),
  _fr("Je le respecte", "Je la respecte"),
  _fr("Pas le plus spectaculaire", "Pas la plus spectaculaire"),
  _fr("je suis un spécialiste", "je suis une spécialiste"),
  _fr("je suis un athlète", "je suis une athlète"),
  _fr("On t'a vu super détendu", "On t'a vue super détendue"),
  _fr("trop discret", "trop discrète"),
  _fr("un peu éteint", "un peu éteinte"),
  _fr("Un grand serveur-volleyeur", "Une grande serveuse-volleyeuse"),
  _fr("Serveur-volleyeur", "Serveuse-volleyeuse"),
  _fr("serveur-volleyeur", "serveuse-volleyeuse"),
  _fr("Concentré, serein", "Concentrée, sereine"),
  _fr("Concentré sur", "Concentrée sur"),
  _fr("(rester|restez) concentré", "$1 concentrée"),
  _fr("Je sors confiant", "Je sors confiante"),
  _fr("Très touché", "Très touchée"),
  _fr("mieux récompensé", "mieux récompensée"),
  _fr("je suis né", "je suis née"),
  _fr("je suis tombé", "je suis tombée"),
  _fr("sortez renforcé", "sortez renforcée"),
  _fr("êtes blanchi", "êtes blanchie"),
  _fr("êtes démasqué", "êtes démasquée"),
  _fr("êtes guéri", "êtes guérie"),
  _fr("êtes gêné", "êtes gênée"),
  _fr("copieusement sifflé", "copieusement sifflée"),
  _fr("Êtes-vous sûr", "Êtes-vous sûre"),
  _fr("l'ambassadeur", "l'ambassadrice"),
  _fr("Adversaire fatigué", "Adversaire fatiguée"),
  _fr("Mené au score, le voilà", "Menée au score, la voilà"),
  _fr("Mené d'un set", "Menée d'un set"),
  _fr("(est|êtes|été|longtemps) mené", "$1 menée"),
  _fr("est breaké", "est breakée"),
  [new RegExp(", breaké" + _E, "gu"), ", breakée"],
  _fr("rester vigilant", "rester vigilante"),
  _fr("semblé inquiété", "semblé inquiétée"),
  _fr("Dos au mur, il a", "Dos au mur, elle a"),
  _fr("On le voyait perdu", "On la voyait perdue"),
  _fr("dominé de la tête", "dominée de la tête"),
  _fr("était trop fort", "était trop forte"),
  _fr("et un (.+?) impressionnant\\.", "et une $1 impressionnante."),
  _fr("où il n'a jamais", "où elle n'a jamais"),
  _fr("qu'il était en bonne posture", "qu'elle était en bonne posture"),
  _fr("est prié", "est priée"),
  _fr("et pourtant il retourne", "et pourtant elle retourne"),
  _fr("et il n'a jamais", "et elle n'a jamais"),
  _fr("On l'a cru", "On l'a crue"),
  _fr("il monte il monte", "elle monte elle monte"),
  _fr("Demi-finalistes éliminés", "Demi-finalistes éliminées"),
  _fr("Gagner un match en 5 sets", "Gagner un match de Grand Chelem en 3 sets"),
  _fr("Les matchs en 5 sets, c'est ça le vrai tennis", "Les matchs en 3 sets, c'est ça le vrai tennis"),
  _fr("Il quitte le circuit", "Elle quitte le circuit"),
  [new RegExp("(\\d+)e mondial\\)", "gu"), "$1e mondiale)"],
  _fr("aussi bien classé", "aussi bien classée"),
  // « X couronnée », mais « Le tournoi a couronné X » (avoir : pas d'accord).
  [new RegExp("(?<!(?:^|[^\\p{L}])a )" + _B + "couronné" + _E, "gu"), "couronnée"],
  // Mini-jeux : l'adversaire au service ou au retour
  _fr("Il attendait", "Elle attendait"),
  _fr("Il avait lu votre service", "Elle avait lu votre service"),
  _fr("Il a servi", "Elle a servi"),
  _fr("Où va-t-il frapper", "Où va-t-elle frapper"),
  _fr("là où il", "là où elle"),
  _fr("CRISPÉ", "CRISPÉE"),
  _fr("crispé", "crispée"),
  _fr("du serveur", "de la serveuse"),
  _fr("le serveur", "la serveuse"),
  _fr("du relanceur", "de la relanceuse"),
  _fr("le relanceur", "la relanceuse"),
  // En match : fil des événements, blessure (smash raté), forme du jour
  _fr("est gêné", "est gênée"),
  _fr("a l'air emprunté", "a l'air empruntée"),
  _fr("BREAKÉ", "BREAKÉE"),
  _fr("QUALIFIÉ", "QUALIFIÉE"),
  _fr("ÉLIMINÉ", "ÉLIMINÉE"),
  _fr("CHAMPION", "CHAMPIONNE"),
  _fr("Blessé", "Blessée"),
  _fr("exempté au", "exemptée au"),
  _fr("Engagé", "Engagée"),
  _fr("surtout fatigué", "surtout fatiguée"),
  _fr("face à un bon passeur", "face à une bonne passeuse"),
  _fr("puissants serveurs", "puissantes serveuses"),
  _fr("puissants frappeurs", "puissantes frappeuses"),
  // Conseils tactiques et dilemmes (l'adversaire)
  _fr("Il est moins endurant que toi\\. Fais-le courir", "Elle est moins endurante que toi. Fais-la courir"),
  _fr("Il passe bien\\.", "Elle passe bien."),
  _fr("Joue court, attire-le au filet", "Joue court, attire-la au filet"),
  _fr("Il aime prendre la balle tôt\\. Joue long, repousse-le", "Elle aime prendre la balle tôt. Joue long, repousse-la"),
  _fr("contre un attaquant, pas un défenseur", "contre une attaquante, pas une défenseuse"),
  _fr("plus de puissance que lui", "plus de puissance qu'elle"),
  _fr("Il frappe fort\\. Défends, laisse-le faire", "Elle frappe fort. Défends, laisse-la faire"),
  _fr("Le faire monter au filet", "La faire monter au filet"),
  _fr("il craque dessus", "elle craque dessus"),
  _fr("est meilleur que vous", "est meilleure que vous"),
  _fr("est pris de court", "est prise de court"),
  _fr("Cette stratégie déstabilise un", "Cette stratégie déstabilise une"),
  _fr("joue le jeu d'un", "joue le jeu d'une"),
  // Profil, styles, humeur
  _fr("Défensif", "Défensive"),
  _fr("Offensif", "Offensive"),
  _fr("Équilibré", "Équilibrée"),
  _fr("Concentré", "Concentrée"),
  _fr("Déterminé", "Déterminée"),
  _fr("Serein", "Sereine"),
  _fr("Inconnu", "Inconnue"),
  _fr("Remarqué", "Remarquée"),
  _fr("Apprécié", "Appréciée"),
  _fr("Modifié", "Modifiée"),
  _fr("([Nn])on classé", "$1on classée"),
  _fr("meilleur vous êtes", "meilleure vous êtes"),
  _fr("(\\d+) premiers", "$1 premières"),
  _fr("trop gourmand", "trop gourmande"),
  // Presse, une du journal, actualité du circuit
  _fr("m'a renforcé", "m'a renforcée"),
  _fr("J'étais cuit", "J'étais cuite"),
  _fr("pleinement satisfait", "pleinement satisfaite"),
  _fr("deux compétiteurs", "deux compétitrices"),
  _fr("Compétiteur de très haut niveau", "Compétitrice de très haut niveau"),
  _fr("Affronter un top", "Affronter une top"),
  _fr("être plus tranchant", "être plus tranchante"),
  _fr("Bien entouré", "Bien entourée"),
  _fr("Je suis humain", "Je suis humaine"),
  _fr("(reviendrai|reviens) plus fort", "$1 plus forte"),
  _fr("Battu en finale", "Battue en finale"),
  _fr("Invité grâce", "Invitée grâce"),
  _fr("sacré au", "sacrée au"),
  _fr("roi du", "reine du"),
  _fr("s'est défait de", "s'est défaite de"),
  _fr("auteur d'une", "autrice d'une"),
  // Réseaux sociaux
  _fr("se sont entraînés ensemble", "se sont entraînées ensemble"),
  _fr("est sous-coté", "est sous-cotée"),
  _fr("d'être cuisinier", "d'être cuisinière"),
  _fr("je suis nul", "je suis nulle"),
  _fr("Le meilleur de tous", "La meilleure de toutes"),
  _fr("Une bio de grand sportif, très inspirant", "Une bio de grande sportive, très inspirante"),
  _fr("dans l'avion, désolé", "dans l'avion, désolée"),
  _fr("les prix, désolé", "les prix, désolée"),
  _fr("Désolé, j'avais un vol", "Désolée, j'avais un vol"),
  _fr("rester vrai", "rester vraie"),
  _fr("On t'a vu râler", "On t'a vue râler"),
  _fr("Ils peuvent venir me le dire en face", "Elles peuvent venir me le dire en face"),
  _fr("Déjà tourné vers", "Déjà tournée vers"),
  _fr("les sportifs les plus suivis", "les sportives les plus suivies"),
  _fr("fier de les représenter", "fière de les représenter"),
  // Vie, défis
  _fr("Sifflé par le public", "Sifflée par le public"),
  _fr("trop occupé", "trop occupée"),
  _fr("rester prudent", "rester prudente"),
  _fr("Un jeune vous demande conseil", "Une jeune vous demande conseil"),
  _fr("Le prendre sous votre aile", "La prendre sous votre aile"),
  _fr("un confrère du circuit", "une consœur du circuit"),
  _fr("Fauché", "Fauchée"),
  _fr("Jeu de terrien", "Jeu de terrienne"),
  _fr("Seul au monde", "Seule au monde"),
  _fr("L'ancien rival", "L'ancienne rivale"),
  _fr("Démasqué", "Démasquée"),
  _fr("N°1 mondial annuel", "N°1 mondiale annuelle"),
  _fr("Vétéran", "Vétérane"),
  _fr("Joué à Paris", "Jouée à Paris"),
  // Défis
  _fr("Ancien n°1 mondial", "Ancienne n°1 mondiale"),
  _fr("Le futur n°1 est-il déjà fini", "La future n°1 est-elle déjà finie"),
  _fr("futur n°1", "future n°1"),
  _fr("Votre grand rival de l'époque, désormais retraité", "Votre grande rivale de l'époque, désormais retraitée"),
  _fr("Un jeune du top 50", "Une jeune du top 50"),
  _fr("Le jeune qui vous admire", "La jeune qui vous admire"),
  _fr("êtes surcoté", "êtes surcotée"),
  _fr("seul jusqu'au bout", "seule jusqu'au bout"),
  _fr("Il ne gagnera jamais", "Elle ne gagnera jamais"),
  _fr("Un concurrent", "Une concurrente"),
  [new RegExp("(\\d+)e mondial" + _E, "gu"), "$1e mondiale"],
  _fr("Le n°1 mondial", "La n°1 mondiale"),
  _fr("n°1 mondial", "n°1 mondiale"),
  // « le n° 5 », « un n°8 » : une joueuse classée
  [new RegExp(_B + "([Ll])e n°(?= ?\\p{N})", "gu"), "$1a n°"],
  [new RegExp(_B + "([Uu])n n°(?= ?\\p{N})", "gu"), "$1ne n°"],
  _fr("représentants", "représentantes"),
  _fr("trop prudent", "trop prudente"),
  _fr("qui t'a marqué", "qui t'a marquée"),
  _fr("a-t-il le physique", "a-t-elle le physique"),
  [new RegExp(_B + "(face à|et|contre) un (?=[\\p{Lu}#])", "gu"), "$1 une "],
  // Trophées et titres de prestige
  _fr("Roi détrôné", "Reine détrônée"),
  _fr("Renard piégé", "Tigresse domptée"),
  _fr("Big Two terrassés", "Big Two terrassées"),
  _fr("Battre C\\. Alcázar", "Battre I. Swiatak"),
  _fr("Battre J\\. Sinterm", "Battre A. Sabalenko"),
  _fr("Battre Sinterm ET Alcázar", "Battre Sabalenko ET Swiatak"),
  [new RegExp(_B + "Roi (du |de l')", "gu"), "Reine $1"],
  _fr("Tueur de géants", "Tueuse de géantes"),
  _fr("Tombeur du Roi", "Tombeuse de la Reine"),
  _fr("Gentleman du gazon", "Lady du gazon"),
  _fr("King of New York", "Queen of New York"),
  _fr("Maître absolu", "Maîtrise absolue"),
  _fr("Chasseur d'élite", "Chasseuse d'élite"),
  _fr("Habitué du circuit", "Habituée du circuit"),
  _fr("Sérieux client", "Sérieuse cliente"),
  _fr("Grand champion", "Grande championne"),
  _fr("Journeyman", "Journeywoman"),
  _fr("Régulier", "Régulière"),
  _fr("Élu", "Élue"),
  _fr("Curieux", "Curieuse"),
  _fr("Terrien", "Terrienne"),
  _fr("Polyvalent", "Polyvalente"),
  _fr("Invaincu", "Invaincue"),
  _fr("Canonnier", "Canonnière"),
  _fr("Collectionneur", "Collectionneuse"),
  // Joueur → joueuse
  _fr("Avec quels joueurs", "Avec quelles joueuses"),
  _fr("Aucun joueur trouvé", "Aucune joueuse trouvée"),
  _fr("tous les joueurs", "toutes les joueuses"),
  _fr("Certains anciens joueurs", "Certaines anciennes joueuses"),
  _fr("Les joueurs du jeu, tirés", "Les joueuses du jeu, tirées"),
  _fr("joueur(s?) personnalisé(s?)", "joueuse$1 personnalisée$2"),
  _fr("meilleurs joueurs mondiaux", "meilleures joueuses mondiales"),
  _fr("Joueur complet", "Joueuse complète"),
  _fr("Joueur confirmé", "Joueuse confirmée"),
  _fr("un joueur inconnu", "une joueuse inconnue"),
  _fr("joueur inconnu", "joueuse inconnue"),
  _fr("du circuit, classés", "du circuit, classées"),
  _fr("meilleurs joueurs", "meilleures joueuses"),
  _fr("meilleur joueur", "meilleure joueuse"),
  _fr("un autre joueur", "une autre joueuse"),
  _fr("([Uu])n joueur", "$1ne joueuse"),
  _fr("([Ll])e joueur", "$1a joueuse"),
  _fr("du joueur", "de la joueuse"),
  _fr("au joueur", "à la joueuse"),
  _fr("([Cc])e joueur", "$1ette joueuse"),
  _fr("Quel joueur", "Quelle joueuse"),
  [new RegExp("(?<!autres |entre )" + _B + "joueurs" + _E, "gu"), "joueuses"],
  _fr("joueur", "joueuse"),
  _fr("Joueurs", "Joueuses"),
  _fr("Joueur", "Joueuse"),
  // Champion, vainqueur, favori…
  _fr("([Uu])n champion", "$1ne championne"),
  _fr("([Ll])e champion", "$1a championne"),
  _fr("champions", "championnes"),
  _fr("champion", "championne"),
  _fr("Champion", "Championne"),
  _fr("([Ll])e vainqueur", "$1a gagnante"),
  _fr("vainqueurs", "gagnantes"),
  _fr("vainqueur", "gagnante"),
  _fr("Vainqueur", "Gagnante"),
  _fr("Gagnant", "Gagnante"),
  _fr("plus d'un favori", "plus d'une favorite"),
  _fr("([Ll])e favori", "$1a favorite"),
  _fr("([Uu])n favori", "$1ne favorite"),
  _fr("favoris", "favorites"),
  _fr("favori", "favorite"),
  _fr("([Uu])n finaliste", "$1ne finaliste"),
  _fr("([Ll])e finaliste", "$1a finaliste"),
  _fr("([Uu])n adversaire", "$1ne adversaire"),
  // Accords des participes (la joueuse)
  _fr("Qualifié", "Qualifiée"),
  _fr("qualifié", "qualifiée"),
  _fr("Éliminé", "Éliminée"),
  _fr("Inscrit", "Inscrite"),
  _fr("inscrit", "inscrite"),
  _fr("blessé", "blessée"),
  // Circuit et catégories ITF
  _fr("Challenger \\(hors calendrier\\)", "WTA 125 (hors calendrier)"),
  _fr("ATP", "WTA"),
  _fr("M25", "W35"),
  _fr("M15", "W15"),
];
export function feminizeText(txt) {
  let out = txt;
  for (const [re, rp] of WTA_TEXT_RULES) out = out.replace(re, rp);
  return out;
}
